name: health_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.0.1+2
  auto_route: ^0.6.9
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  fl_chart: ^0.12.2
  flutter_image_utilities: ^0.0.4
  flutter_native_splash: ^0.2.8
  font_awesome_flutter: ^8.11.0
  freezed_annotation: ^0.12.0
  get_it: ^5.0.4
  google_sign_in: ^4.5.6
  injectable: ^1.0.5
  json_annotation: ^3.1.1
  path_provider: ^1.6.27
  permission_handler: ^5.0.1+1
  printing: ^4.0.0
  screenshot: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  flutter_launcher_icons: ^0.8.1
  freezed: ^0.12.7
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.1
  lint: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/health.png
    - assets/images/google.png
    - assets/images/profile.png
    - assets/images/user.png
    - assets/images/background.png
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript/DancingScript-Regular.ttf
        - asset: assets/fonts/DancingScript/DancingScript-Medium.ttf
        - asset: assets/fonts/DancingScript/DancingScript-SemiBold.ttf
        - asset: assets/fonts/DancingScript/DancingScript-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-ThinItalic.ttf

flutter_native_splash:
  color: "#6C00B2"
  image: assets/images/health.png

flutter_icons:
  image_path: 'assets/images/health.png'
  android: true